const fs=require('node:fs');const path=require('node:path');const root=path.join(__dirname,'..');let pass=true;
function check(name,ok,detail=''){console.log(`${ok?'PASS':'FAIL'} ${name}${detail?' - '+detail:''}`);pass=pass&&ok}
const required=['server.js','render.yaml','package.json','index.html','success.html','ip.html','engine.html','revenue.html','register.html','dreamiez/register.html','dreamiez/login.html','dreamiez/index.html','mtg.html','kelplantis.html','assets/shared-asset-schema.json','catalog/products/COMMANDER-DECK-DIAGNOSTIC-001.json'];
for(const rel of required)check(rel,fs.existsSync(path.join(root,rel)));
const productDir=path.join(root,'catalog','products');
const productFiles=fs.existsSync(productDir)?fs.readdirSync(productDir).filter(x=>x.endsWith('.json')):[];
const products=productFiles.map(x=>{try{return JSON.parse(fs.readFileSync(path.join(productDir,x),'utf8'));}catch(e){check(`JSON ${x}`,false,e.message);return null;}}).filter(Boolean);
const ids=new Set();
for(const p of products){check(`product id ${p.id||'<missing>'}`,typeof p.id==='string'&&p.id.length>0&&!ids.has(p.id),ids.has(p.id)?'duplicate id':'');if(p.id)ids.add(p.id);if(String(p.silo||'').toUpperCase()==='MTG'){check(`MTG ${p.id} status`,['published','draft','quarantine'].includes(p.status),'valid lifecycle state');if(p.status==='published'){check(`MTG ${p.id} price`,Number.isFinite(Number(p.price_nzd??p.price))||!!p.prices,'NZD price present');check(`MTG ${p.id} stock`,Number.isInteger(Number(p.stock))&&Number(p.stock)>=0,'non-negative integer stock');if(p.checkout_available===true)check(`MTG ${p.id} Stripe mapping`,!!p.stripe_price_env&&typeof p.stripe_price_env==='object','checkoutable product has explicit Stripe price mapping');}}}
const product=JSON.parse(fs.readFileSync(path.join(productDir,'COMMANDER-DECK-DIAGNOSTIC-001.json')));check('Commander offer active',product.checkout_available===true&&product.approval_required===false,'checkout enabled and approval gate cleared');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');check('server offer catalog merge',server.includes('function publicOffers()')&&server.includes('catalogMtgOffers()'));check('server offer active',server.includes("checkout_available: true, approval_required: false"));check('checkout POST route',server.includes("app.post('/api/offer-checkout/create'"));check('checkout uses server-side Stripe price',server.includes('stripePriceEnvFor')&&server.includes('process.env[priceEnv]'));check('checkout blocks unmapped catalog prices',server.includes('offer-specific Stripe price mapping missing'));check('live-mode webhook guard',server.includes("if (!s.livemode)")&&server.includes("Ignoring test-mode session"));check('webhook signature verification',server.includes('constructEvent'));check('real payment fossil only',server.includes('FIRST_PAYMENT_PROOF.json'));check('public MTG route alias',server.includes("'/mtg': 'mtg.html'"));
const mtg=fs.readFileSync(path.join(root,'mtg.html'),'utf8');check('MTG surface calls offers API',mtg.includes("fetch('/api/offers',"));check('MTG surface has secure Stripe buy CTA',/Buy securely with Stripe/i.test(mtg));check('MTG surface uses canonical offer checkout',mtg.includes("fetch('/api/offer-checkout/create'")&&mtg.includes('offer_id'));check('MTG surface does not assert obsolete product_id checkout wiring',!mtg.includes("product_id:btn.getAttribute('data-product')")&&!mtg.includes("fetch('/api/checkout/create'"));check('MTG surface hard-filter present',mtg.includes(".filter(function(o){return String(o&&o.silo||'').toUpperCase()==='MTG';})"));check('MTG surface excludes known Dreamiez contamination',!mtg.includes('Dreamiez Brush Roll')&&!mtg.includes('Dreamiez Cosmetic Pouch')&&!mtg.includes('Cosmic Hoodie'));
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');check('neutral horizontal carousel',index.includes('overflow-x:auto')&&index.includes('scroll-snap-type:x mandatory'));check('silo names',index.includes('Dreamiez')&&index.includes('Kelplantis')&&index.includes('MTG')&&index.includes('BEC-PRIME'));check('front door has no stale approval claim',!index.includes('approval registry is empty'));
const ip=fs.readFileSync(path.join(root,'ip.html'),'utf8');for(const term of ['Constitution','CUBE Compiler','Multi-LLM','Persistent Economic Memory','Browning Gauntlet','Commerce Spine','Fossil Evidence','Independent Silos','Demand Radar','Elohim Refinery','Truth Boundary','Neutral Front Door','Humaniser','Approval Governor','Revenue OS','Digital Proxy','Silo Integrity'])check('IP '+term,ip.includes(term));
const engine=fs.readFileSync(path.join(root,'engine.html'),'utf8');check('engine loop',engine.includes('DEMAND')&&engine.includes('REFINE')&&engine.includes('GAUNTLET')&&engine.includes('COMPILE')&&engine.includes('DISTRIBUTE')&&engine.includes('CHECKOUT')&&engine.includes('PAYMENT')&&engine.includes('FOSSIL')&&engine.includes('MEMORY')&&engine.includes('ITERATE'));
const revenue=fs.readFileSync(path.join(root,'revenue.html'),'utf8');check('revenue uses canonical offers API',revenue.includes("fetch('/api/offers'")&&revenue.includes('canonical offers API'));check('revenue does not claim empty approval registry',!revenue.includes('approval registry is currently empty'));check('revenue preserves payment evidence rule',revenue.includes('signed live payment webhook')&&revenue.includes('not payment evidence'));
const success=fs.readFileSync(path.join(root,'success.html'),'utf8');check('checkout return does not claim payment proof',success.includes('Checkout returned')&&success.includes('Payment is not proven here'));
const assets=JSON.parse(fs.readFileSync(path.join(root,'assets/shared-asset-schema.json')));check('shared asset schema',assets.schema_version==='BEC-SHARED-ASSET-1.0'&&assets.silos.includes('DREAMIEZ')&&assets.silos.includes('KELPLANTIS'));
const dream=fs.readFileSync(path.join(root,'dreamiez/index.html'),'utf8');check('Dreamiez face customization',dream.includes('faceSelect'));check('Dreamiez streak persistence',dream.includes('localStorage')&&dream.includes('streak'));check('daily cosmetic gate',dream.includes('claimed')&&dream.includes('Daily cosmetic'));check('Dreamiez has no MTG checkout surface',!/COMMANDER-DECK|MTG|offer-checkout/i.test(dream));
const marketplace=fs.readFileSync(path.join(root,'marketplace.html'),'utf8');check('B2B marketplace surface',marketplace.includes('B2B MARKETPLACE')&&marketplace.includes('/api/marketplace/catalog'));check('B2B marketplace has no MTG checkout path',!marketplace.includes('/api/offer-checkout/create')&&!marketplace.includes('COMMANDER-DECK-DIAGNOSTIC-001'));
const fossil=path.join(root,'Proof/Fossils/FIRST_PAYMENT_PROOF.json');if(fs.existsSync(fossil)){const f=JSON.parse(fs.readFileSync(fossil));check('FIRST_PAYMENT_PROOF live transaction evidence',f.status==='PASS'&&typeof f.transaction_id==='string'&&f.transaction_id.length>0)}else console.log('INFO FIRST_PAYMENT_PROOF not present: no live payment has been observed yet');
console.log(pass?'VERIFY PASS':'VERIFY FAIL');process.exitCode=pass?0:1;